real_effort/models.py
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)


def levenshtein(a, b):
    """Calculates the Levenshtein distance between a and b."""
    n, m = len(a), len(b)
    if n > m:
        # Make sure n <= m, to use O(min(n, m)) space
        a, b = b, a
        n, m = m, n

    current = range(n + 1)

    for i in range(1, m + 1):
        previous, current = current, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete = previous[j] + 1, current[j - 1] + 1
            change = previous[j - 1]

            if a[j - 1] != b[i - 1]:
                change = change + 1
            current[j] = min(add, delete, change)

    return current[n]


def distance_and_ok(transcribed_text, reference_text, max_error_rate):
    error_threshold = len(reference_text) * max_error_rate
    distance = levenshtein(transcribed_text, reference_text)
    ok = distance <= error_threshold
    return distance, ok

class Constants(BaseConstants):
    name_in_url = 'real_effort'
    num_rounds = 10 #10 para los pilotos/produccion
    #num_groups = 1
    players_per_group = None
    info_code = 'real_effort/Code.html'

    #List of the incomprehensible text that the players must transcribe
    reference_texts = [
        "Revealed preference",
        "Hex ton satoha egavecen. Loh ta receso minenes da linoyiy xese coreliet ocotine! Senuh asud tu bubo "
        "tixorut sola, bo ipacape le rorisin lesiku etutale saseriec niyacin ponim na. Ri arariye senayi esoced "
        "behin? Tefid oveve duk mosar rototo buc: Leseri binin nolelar sise etolegus ibosa farare. Desac eno "
        "titeda res vab no mes!",
    ]

    maxdistance1 = len(reference_texts[0])
    maxdistance2 = len(reference_texts[1])

    allowed_error_rates = [0, 0.2]
    difficulty = 1
    ratio = 1
    endowment = 2
    income = 0


class Subsession(BaseSubsession):
    pass



class Group(BaseGroup):
    baseIncome = models.CurrencyField()
    total_report = models.CurrencyField()
    #total_contribution = models.CurrencyField()
    total_earnings = models.CurrencyField()
    #individual_share = models.CurrencyField()
    temp = models.IntegerField()
    transcription_required = models.BooleanField() # True if required, else False
    treatment_tag = models.StringField() # tag of current treatment
    transcription_difficulty = models.IntegerField()


class Player(BasePlayer):
    transcribed_text = models.LongStringField()
    transcribed_text2 = models.LongStringField()
    levenshtein_distance = models.IntegerField()
    ratio = models.FloatField()
    done = models.BooleanField()
    transcriptionDone = models.BooleanField()
    income = models.CurrencyField()
    refText = models.LongStringField()

real_effort/templates/real_effort/InstructionsB.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block content %}

<head>
<style>
h2 {
        color: #F8F4EE;
}
</style>
</head>
<body>
<div class="card bg-light instructions">
    <div class="card-body">

    <h3>
        10 tareas de transcripción
    </h3>

    <p>
        <div align="justify">

            A continuación, deberá resolver el requerimiento mínimo de 10 tareas de transcripción para la sesión de hoy
            <br><br>
            {% next_button %}
    </div>
</div>
</body>


{% endblock %}

real_effort/templates/real_effort/Transcribe.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Transcripción {{ subsession.round_number }}/{{ Constants.num_rounds }}
{% endblock %}

{% block content %}
        <p> Trascribe el siguiente texto en el recuadro.</p>
        <p> Trata de ser exacto y asegúrate de poner todas las letras, símbolos y espacios correspondientes.</p>
    
    {% endif %}


    <img src="{% static image_path %}"/>
    <br><br>


    {% formfield player.transcribed_text label="" %}

    {% next_button %}

    {% if debug %}
        <div class="card border-warning">
            <div class="card-body">
            <h4>Explanation for researchers (shown in debug mode only)</h4>
            <p>
                
                by clicking <a href="#" id="prefill">this link</a>
                and clicking "next".
            </p>

            <p>
                A subject can only advance to the next screen if the
                transcription is {{ required_accuracy }}% accurate.
            </p>

            </div>
        </div>

    {% endif %}
{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        var referenceText = {{ reference_text|json }};
        $('#prefill').click(function () {
            $('#id_transcribed_text').val(referenceText);
        })
    });
</script>
{% endblock %}

real_effort/templates/real_effort/Transcribe1.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Transcripción
{% endblock %}

{% block content %}

        <p> Trascribe el siguiente texto en el recuadro.</p>
<p>Trata de ser exacto y asegúrate de poner todas las letras y espacios correspondientes.</p>


    {% formfield player.transcribed_text2 label="" %}

    {% next_button %}

{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        var referenceText = {{ reference_text|json }};
        $('#prefill').click(function () {
            $('#id_transcribed_text').val(referenceText);
        })
    });
</script>
{% endblock %}

real_effort/templates/real_effort/Transcribe2.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    Transcripción - Ronda {{ counter }}
{% endblock %}

{% block content %}

        <p> Trascribe el siguiente texto en el recuadro.</p>
        <p> Trata de ser exacto y asegúrate de poner todas las caracteres correspondientes.</p>



    <img src="{% static image_path %}"/>
    <br><br>


    {% formfield player.transcribed_text label="" %}

    {% next_button %}

{% endblock %}

{% block scripts %}
<script>
    $(document).ready(function () {
        var referenceText = {{ reference_text|json }};
        $('#prefill').click(function () {
            $('#id_transcribed_text').val(referenceText);
        })
    });
</script>
{% endblock %}

real_effort/templates/real_effort/part2.html
{% extends "global/Page.html" %}
{% load otree static %}

{% block title %}
    <p style="font-size:15px; color:#CD853F;" align="right">{{ pgCode }}<br/>Periodo {{ round_num }}</p>
    Resultados de la transcripción y Reporte de Ingresos
{% endblock %}

{% block content %}
    {% if group.spanish %}
        {% if transcribe_on %}
        <p> La precisión de tu transcripción fue de {{ display_ratio }}%.</p>
        <p>Por lo tanto, tu ingreso es de un {{ display_ratio }}% de {{ endowment }} Solex, lo cual resulta en {{ display_income }} Solex.
        </p>
        {% else %}
        <p> Tu ingreso es  {{ display_income }} Solex.</p>
        {% endif %}
        <p>
            Reporte de Ingreso:
            <br/>
            La tasa impositiva es {{ tax }}%.
            <br/><br/>
            En el siguiente recuadro, ingresa el monto que reportarás como ingreso.
        </p>

        {% formfield player.contribution label="¿Cuál es el monto que reportarás como ingreso?" %}
        <p> Recuerda que el monto total recolectado de tu grupo será multiplicado por {{ mult }} y luego será divido entre todos los miembros del grupo, sin importar cuánto contribuyó cada uno.
    </p>
        {% endif %}
    {% else %}
        {% if transcribe_on %}
            <p>
                The accuracy of your transcription was {{ display_ratio }}%.
                <br/>
                Therefore, your income is {{ display_ratio }}% of {{ endowment }} ECUs, which is {{ display_income }} ECUs.
            </p>
        {% else %}
            Your income is {{ display_income }} ECUs.
            <br/><br/>
        {% endif %}
        <p>
            Reporting Income:
            <br/>
            The tax rate is {{ tax }}%.
            <br/><br/>
            Please, in the field below, report your income for tax collection.
        </p>

        {% formfield player.contribution label="How much income will you report?" %}
    <p> Remember that the total tax collected from all group members is added together, multiplied by {{ mult }}, and then
        divided evenly among all group members, regardless of how much each contributed.
    </p>
    {% endif %}

    {% next_button %}
    <p>
        {% include Constants.contact_template %}
    </p>

{% endblock %}