demograp_es/models.py
# -*- coding: utf-8 -*-
# <standard imports>
from __future__ import division
from otree.db import models
from otree.constants import BaseConstants
from otree.models import BaseSubsession, BaseGroup, BasePlayer
from django.utils.translation import ugettext_lazy as _
from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)
from otree.common import Currency as c, currency_range
import random
# </standard imports>




class Constants(BaseConstants):
    name_in_url = 'demograp_es'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):
    time_Demographics = models.TextField(widget=widgets.HiddenInput(attrs={'id': 'arrive_time'}))
    time_CognitiveReflectionTest = models.TextField(widget=widgets.HiddenInput(attrs={'id': 'arrive_time'}))

    def set_payoff(self):
        """Calculate payoff, which is zero for the survey"""
        self.payoff = 0

    q_country = models.CharField(verbose_name=_('What country are you from?'))

    q_major = models.CharField(verbose_name=_('What is your major?'))

    q_age = models.PositiveIntegerField(verbose_name=_('What is your age?'),
                                        min=18,
                                        max=120)

    q_school_year = models.CharField(initial=None,
                                 verbose_name=_('What is your school year?'),
                                 choices=[_('Freshman'), _('Sophomore'),_('Junior'),_('Senior'),_('Postgraduate'),_('Other')],
                                 widget=widgets.RadioSelect())

    q_station = models.PositiveIntegerField(verbose_name=_('What is your computer station number? (see white sticker on computer or ask experimenter)'),
                                        choices=range(1, 24),
                                        initial=None)

    q_gender = models.CharField(verbose_name=_('What do you identify as?'))

    q_income = models.PositiveIntegerField(verbose_name=_('What is the approximate annual income of your family?'),
                                           choices=[
                                               [1, _('less than $15,000')],
                                               [2, '$15,000 - $29,999'],
                                               [3, '$30,000 - $59,999'],
                                               [4, '$60,000 - $99,999'],
                                               [5, '$100,000 - $199,999'],
                                               [6, '$200,000 or more'],
                                               [7, _('I rather not answer this question')],
                                           ]
                                           )

    q_zipcode = models.PositiveIntegerField(verbose_name=_('What is the zip code where you grew up?'))

    q_opinion = models.CharField(initial=None,
                                 verbose_name=_('Were the instructions provided in this experiment clear and useful?'),
                                 choices=[_('Yes'), 'No'],
                                 widget=widgets.RadioSelect())

    q_linda = models.CharField(initial=None,
                                 verbose_name=_('Linda is 31 years old, single, outspoken, and very bright. She majored in philosophy. As a student, she was deeply concerned with issues of discrimination and social justice, and also participated in anti-nuclear demonstrations.\n\n Which of the following two alternatives is more probable?'),
                                 choices=[_('Linda is a bank teller.'), _('Linda is a bank teller and active in the feminist movement.')],
                                 widget=widgets.RadioSelect())

    q_monty = models.CharField(initial=None,
                                 verbose_name=_('Assume that a room is equipped with three doors. Behind two are goats, and behind the third is a shiny new car. You are asked to pick a door, and will win whatever is behind it. Someone who knows what is behind the doors opens one of the other two, revealing a goat and asks you if you wish to change your selection, you:'),
                                 choices=[_('change the door.'), _('do not change the door.')],
                                 widget=widgets.RadioSelect())

    q_how = models.CharField(verbose_name=_('How did you make your choices?'))

    q_rule = models.CharField(verbose_name=_('Did you have any rule you applied to your choices?'))

    q_number = models.PositiveIntegerField(verbose_name=_('How many studies have you participated in?'))

    crt_bat = models.PositiveIntegerField()

    crt_widget = models.PositiveIntegerField()

    crt_lake = models.PositiveIntegerField()

demograp_es/_builtin/__init__.py
# Don't change anything in this file.
from .. import models
import otree.views
import otree.test
from otree.common import Currency as c, currency_range

class Page(otree.views.Page):
    z_models = models

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.views.WaitPage):

    z_models = models

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.test.Bot):

    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

demograp_es/views.py
# -*- coding: utf-8 -*-
from __future__ import division
from . import models
from ._builtin import Page, WaitPage
from otree.common import Currency as c, currency_range
from .models import Constants


class Demographics(Page):
    form_model = models.Player
    form_fields = ['q_number', 'q_major','q_school_year','q_how','q_rule','q_country',
                   'q_age',
                   'q_gender',
                   'q_income',
                   'q_zipcode',
                   'q_opinion',
                   'time_Demographics',
                   'q_station'
                   ]


class CognitiveReflectionTest(Page):
    form_model = models.Player
    form_fields = ['q_linda','q_monty','crt_bat',
                   'crt_widget',
                   'crt_lake',
                   'time_CognitiveReflectionTest',
                   ]

    def before_next_page(self):
        self.player.set_payoff()


page_sequence = [
    Demographics,
    CognitiveReflectionTest,

]

demograp_es/templates/demograp_es/CognitiveReflectionTest.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}
{% load otree  i18n %}

{% block title %}
    {% blocktrans trimmed %}Anonymous Survey{% endblocktrans %}
{% endblock %}
{% block scripts %}
    {# this records the timestamp #}
    <script type="text/javascript">
            window.onload = function () {
                document.getElementById("arrive_time").value = (new Date()).toISOString();
            }
    </script>
{% endblock %}
{% block content %}
<input type="hidden" name="time_CognitiveReflectionTest" id="arrive_time">

    <p>
        {% blocktrans %}Please answer the following questions.{% endblocktrans %}
    </p>
    {% formfield player.q_linda %}
    {% formfield player.q_monty %}
    {% formfield player.crt_bat with label=_("A bat and a ball cost 22 dollars in total. The bat costs 20 dollars more than the ball. How many dollars does the ball cost?") %}
    {% formfield player.crt_widget with label=_("If it takes 5 machines 5 minutes to make 5 widgets, how many minutes would it take 100 machines to make 100 widgets?") %}
    {% formfield player.crt_lake with label=_("In a lake, there is a patch of lily pads. Every day, the patch doubles in size.If it takes 48 days for the patch to cover the entire lake, how many days would it take for the patch to cover half of the lake?") %}
    {% next_button %}

{% endblock %}

demograp_es/templates/demograp_es/Demographics.html
{% extends "global/Base.html" %}
{% load staticfiles otree_tags %}
{% load otree  i18n %}

{% block title %}
    {% blocktrans trimmed %}Anonymous Survey{% endblocktrans %}
{% endblock %}

{% block scripts %}
    {# this records the timestamp #}
    <script type="text/javascript">
            window.onload = function () {
                document.getElementById("arrive_time").value = (new Date()).toISOString();
            }
    </script>
{% endblock %}

{% block content %}
    <input type="hidden" name="time_Demographics" id="arrive_time">

    <p>
        {% blocktrans %}Please answer the following questions.{% endblocktrans %}
    </p>
   

    {% formfield player.q_number %}
    <br/>
    {% formfield player.q_age %}
    <br/>
    {% formfield player.q_major %}
    <br/>
    {% formfield player.q_gender %}
    <br/>
    {% formfield player.q_school_year %}
    <br/>
    {% formfield player.q_income %}
    <br/>
    {% formfield player.q_zipcode %}
    <br/>
    {% formfield player.q_country %}
    <br/>
    {% formfield player.q_opinion %}
    <br/>
    {% formfield player.q_station %}
    <br/>
    {% formfield player.q_how %}
    <br/>
    {% formfield player.q_rule %}
    <br/>

    {% next_button %}

{% endblock %}

{% block content_at_bottom_of_body %}

    <script type="text/javascript">
        function sort(a, b) {
            return (a.innerHTML > b.innerHTML) ? 1 : -1;
        }
        $('#id_q_country option').sort(sort).appendTo('#id_q_country');
    </script>

{% endblock %}